# Generated by Django 6.0.4 on 2026-04-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GERANT', 'Gérant'), ('VENDEUR', 'Vendeur')], default='VENDEUR', max_length=10, verbose_name='Rôle'),
        ),
    ]
