services:
  docs:
    image: erp_sylla_local_docs
    container_name: erp_sylla_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./erp_sylla:/app/erp_sylla:z
    ports:
      - '9000:9000'
    command: /start-docs
