# Generated by Django 6.0.4 on 2026-05-02 21:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=100, unique=True, verbose_name='N° Conteneur')),
                ('order_reference', models.CharField(blank=True, max_length=100, verbose_name='Réf Commande')),
                ('origin_port', models.CharField(blank=True, max_length=100, verbose_name='Port de départ')),
                ('destination_port', models.CharField(blank=True, max_length=100, verbose_name="Port d'arrivée")),
                ('main_product', models.CharField(blank=True, max_length=255, verbose_name='Produit principal')),
                ('container_type', models.CharField(blank=True, max_length=50, verbose_name='Type conteneur')),
                ('quantity_packages', models.PositiveIntegerField(default=0, verbose_name='Quantité / Colis')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Date commande')),
                ('loading_date', models.DateField(blank=True, null=True, verbose_name='Date chargement')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='ETD (Départ prévu)')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA (Arrivée prévue)')),
                ('actual_arrival_date', models.DateField(blank=True, null=True, verbose_name='Date arrivée réelle')),
                ('merchandise_value', models.PositiveBigIntegerField(default=0, verbose_name='Valeur marchandise (FCFA)')),
                ('total_expenses', models.PositiveBigIntegerField(default=0, verbose_name='Total frais (FCFA)')),
                ('status', models.CharField(choices=[('ORDERED', 'Commandé'), ('LOADING', 'Chargement'), ('IN_TRANSIT', 'En mer (Transit)'), ('ARRIVED_PORT', 'Arrivé au port'), ('CUSTOMS', 'Dédouanement'), ('ARRIVED', "Arrivé à l'entrepôt"), ('CANCELLED', 'Annulé')], default='ORDERED', max_length=20, verbose_name='Statut')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conteneur',
                'verbose_name_plural': 'Conteneurs',
                'ordering': ['-eta', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du fournisseur')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Contact')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Fournisseur Logistique',
                'verbose_name_plural': 'Fournisseurs Logistique',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContainerExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Libellé du frais')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Montant (FCFA)')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date du frais')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='logistics.container')),
            ],
            options={
                'verbose_name': 'Frais Conteneur',
                'verbose_name_plural': 'Frais Conteneurs',
            },
        ),
        migrations.CreateModel(
            name='HistoricalContainerExpense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Libellé du frais')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Montant (FCFA)')),
                ('date', models.DateField(blank=True, editable=False, verbose_name='Date du frais')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('container', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.container')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Frais Conteneur',
                'verbose_name_plural': 'historical Frais Conteneurs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLogisticsSupplier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du fournisseur')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Contact')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Fournisseur Logistique',
                'verbose_name_plural': 'historical Fournisseurs Logistique',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalContainer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('container_number', models.CharField(db_index=True, max_length=100, verbose_name='N° Conteneur')),
                ('order_reference', models.CharField(blank=True, max_length=100, verbose_name='Réf Commande')),
                ('origin_port', models.CharField(blank=True, max_length=100, verbose_name='Port de départ')),
                ('destination_port', models.CharField(blank=True, max_length=100, verbose_name="Port d'arrivée")),
                ('main_product', models.CharField(blank=True, max_length=255, verbose_name='Produit principal')),
                ('container_type', models.CharField(blank=True, max_length=50, verbose_name='Type conteneur')),
                ('quantity_packages', models.PositiveIntegerField(default=0, verbose_name='Quantité / Colis')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Date commande')),
                ('loading_date', models.DateField(blank=True, null=True, verbose_name='Date chargement')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='ETD (Départ prévu)')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA (Arrivée prévue)')),
                ('actual_arrival_date', models.DateField(blank=True, null=True, verbose_name='Date arrivée réelle')),
                ('merchandise_value', models.PositiveBigIntegerField(default=0, verbose_name='Valeur marchandise (FCFA)')),
                ('total_expenses', models.PositiveBigIntegerField(default=0, verbose_name='Total frais (FCFA)')),
                ('status', models.CharField(choices=[('ORDERED', 'Commandé'), ('LOADING', 'Chargement'), ('IN_TRANSIT', 'En mer (Transit)'), ('ARRIVED_PORT', 'Arrivé au port'), ('CUSTOMS', 'Dédouanement'), ('ARRIVED', "Arrivé à l'entrepôt"), ('CANCELLED', 'Annulé')], default='ORDERED', max_length=20, verbose_name='Statut')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.logisticssupplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'historical Conteneur',
                'verbose_name_plural': 'historical Conteneurs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='container',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='logistics.logisticssupplier', verbose_name='Fournisseur'),
        ),
    ]
