# Generated by Django 6.0.4 on 2026-04-11 20:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_historicalstocktransaction_to_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSale',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, verbose_name='N° Facture/Devis')),
                ('type', models.CharField(choices=[('SALE', 'Vente validée'), ('QUOTE', 'Devis / Proforma')], default='SALE', max_length=10, verbose_name='Type')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='Montant Total')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('MOMO', 'Mobile Money'), ('TRANSFER', 'Virement'), ('CREDIT', 'Crédit / Dette')], default='CASH', max_length=20, verbose_name='Mode de paiement')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Vente',
                'verbose_name_plural': 'historical Ventes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='N° Facture/Devis')),
                ('type', models.CharField(choices=[('SALE', 'Vente validée'), ('QUOTE', 'Devis / Proforma')], default='SALE', max_length=10, verbose_name='Type')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='Montant Total')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('MOMO', 'Mobile Money'), ('TRANSFER', 'Virement'), ('CREDIT', 'Crédit / Dette')], default='CASH', max_length=20, verbose_name='Mode de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('unit', models.CharField(choices=[('PIECE', 'Pièce'), ('CARTON', 'Carton')], max_length=10, verbose_name='Unité')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Prix unitaire appliqué')),
                ('total_line', models.PositiveIntegerField(verbose_name='Total ligne')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
