# Generated by Django 6.0.4 on 2026-04-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='COMPLETED', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='COMPLETED', max_length=20, verbose_name='Statut'),
        ),
    ]
