# Generated by Django 6.0.4 on 2026-04-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_historicalsale_status_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Format international (ex: +22370000000)', max_length=20, null=True, verbose_name='Téléphone Client (WhatsApp)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Format international (ex: +22370000000)', max_length=20, null=True, verbose_name='Téléphone Client (WhatsApp)'),
        ),
    ]
