# Generated by Django 6.0.4 on 2026-04-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_customer_historicalsale_customer_sale_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du client (Passage)'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du client (Passage)'),
        ),
    ]
