# Generated by Django 6.0.4 on 2026-04-20 12:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_historicalproduct_alert_threshold_cartons_and_more'),
        ('sales', '0005_historicalsale_customer_name_sale_customer_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsale',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Vente / Devis', 'verbose_name_plural': 'historical Ventes / Devis'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vente / Devis', 'verbose_name_plural': 'Ventes / Devis'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Ligne de vente', 'verbose_name_plural': 'Lignes de vente'},
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_line',
            field=models.PositiveIntegerField(default=0, verbose_name='Total ligne'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='Prix unitaire (au moment de la vente)'),
        ),
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Montant versé')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('MOMO', 'Mobile Money'), ('TRANSFER', 'Virement')], default='CASH', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(db_index=True, max_length=50, verbose_name='Référence / N° de reçu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('balance_after', models.IntegerField(blank=True, null=True, verbose_name='Solde après versement')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Paiement Client',
                'verbose_name_plural': 'historical Paiements Clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSaleItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('unit', models.CharField(choices=[('PIECE', 'Pièce'), ('CARTON', 'Carton')], max_length=10, verbose_name='Unité')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Prix unitaire (au moment de la vente)')),
                ('total_line', models.PositiveIntegerField(default=0, verbose_name='Total ligne')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.product')),
                ('sale', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.sale')),
            ],
            options={
                'verbose_name': 'historical Ligne de vente',
                'verbose_name_plural': 'historical Lignes de vente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Montant versé')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('MOMO', 'Mobile Money'), ('TRANSFER', 'Virement')], default='CASH', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence / N° de reçu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('balance_after', models.IntegerField(blank=True, null=True, verbose_name='Solde après versement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.customer')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement Client',
                'verbose_name_plural': 'Paiements Clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
