# Generated by Django 6.0.4 on 2026-04-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_historicalsale_options_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['-id'], 'verbose_name': 'Ligne de vente', 'verbose_name_plural': 'Lignes de vente'},
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('ORANGE', 'Orange Money'), ('WAVE', 'Wave'), ('MOOV', 'Moov Money'), ('CHEQUE', 'Chèque')], default='CASH', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone Client (WhatsApp)'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('ORANGE', 'Orange Money'), ('WAVE', 'Wave'), ('MOOV', 'Moov Money'), ('CHEQUE', 'Chèque'), ('CREDIT', 'Crédit / Dette')], default='CASH', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('ORANGE', 'Orange Money'), ('WAVE', 'Wave'), ('MOOV', 'Moov Money'), ('CHEQUE', 'Chèque')], default='CASH', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone Client (WhatsApp)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('ORANGE', 'Orange Money'), ('WAVE', 'Wave'), ('MOOV', 'Moov Money'), ('CHEQUE', 'Chèque'), ('CREDIT', 'Crédit / Dette')], default='CASH', max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
