# Generated by Django 6.0.4 on 2026-05-15 10:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_saleitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité retournée'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantité retournée'),
        ),
        migrations.CreateModel(
            name='HistoricalProductReturn',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('total_refund_amount', models.PositiveIntegerField(default=0, verbose_name='Montant total remboursé')),
                ('reason', models.TextField(blank=True, verbose_name='Motif du retour')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.sale')),
            ],
            options={
                'verbose_name': 'historical Retour de produit',
                'verbose_name_plural': 'historical Retours de produits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_refund_amount', models.PositiveIntegerField(default=0, verbose_name='Montant total remboursé')),
                ('reason', models.TextField(blank=True, verbose_name='Motif du retour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('returned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Retour de produit',
                'verbose_name_plural': 'Retours de produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité retournée')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Prix unitaire au moment du retour')),
                ('product_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.productreturn')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.saleitem')),
            ],
        ),
    ]
