# Generated by Django 6.0.4 on 2026-05-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_historicalsaleitem_returned_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée'), ('PARTIAL_RETURN', 'Retour Partiel')], default='COMPLETED', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée'), ('PARTIAL_RETURN', 'Retour Partiel')], default='COMPLETED', max_length=20, verbose_name='Statut'),
        ),
    ]
