# Generated by Django 6.0.4 on 2026-04-14 11:54

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setup_initial_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReleaseCode',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Code')),
                ('operation_type', models.CharField(choices=[('DISCOUNT', 'Remise exceptionnelle'), ('CANCEL', 'Annulation de transaction'), ('STOCK_ADJ', 'Ajustement de stock manuel'), ('OTHER', 'Autre opération sensible')], default='DISCOUNT', max_length=20, verbose_name="Type d'opération")),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Code de déblocage',
                'verbose_name_plural': 'historical Codes de déblocage',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ReleaseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('operation_type', models.CharField(choices=[('DISCOUNT', 'Remise exceptionnelle'), ('CANCEL', 'Annulation de transaction'), ('STOCK_ADJ', 'Ajustement de stock manuel'), ('OTHER', 'Autre opération sensible')], default='DISCOUNT', max_length=20, verbose_name="Type d'opération")),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_codes', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code de déblocage',
                'verbose_name_plural': 'Codes de déblocage',
                'ordering': ['-created_at'],
            },
        ),
    ]
