# Generated by Django 6.0.4 on 2026-04-23 23:38

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalreleasecode_releasecode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
            },
        ),
        migrations.AlterModelOptions(
            name='audittestmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historicalaudittestmodel',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical audit test model', 'verbose_name_plural': 'historical audit test models'},
        ),
        migrations.AlterModelOptions(
            name='historicalreleasecode',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical release code', 'verbose_name_plural': 'historical release codes'},
        ),
        migrations.AlterModelOptions(
            name='releasecode',
            options={},
        ),
        migrations.RemoveField(
            model_name='audittestmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='audittestmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalaudittestmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalaudittestmodel',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='historicalreleasecode',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalreleasecode',
            name='operation_type',
            field=models.CharField(choices=[('DISCOUNT', 'Remise exceptionnelle'), ('CANCEL', 'Annulation de vente'), ('STOCK', 'Ajustement de stock')], max_length=20, verbose_name='Opération'),
        ),
        migrations.AlterField(
            model_name='releasecode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='releasecode',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='releasecode',
            name='operation_type',
            field=models.CharField(choices=[('DISCOUNT', 'Remise exceptionnelle'), ('CANCEL', 'Annulation de vente'), ('STOCK', 'Ajustement de stock')], max_length=20, verbose_name='Opération'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Motif / Titre')),
                ('amount', models.PositiveIntegerField(verbose_name='Montant (F CFA)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de la dépense')),
                ('notes', models.TextField(blank=True, verbose_name='Notes complémentaires')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/receipts/', verbose_name='Justificatif (Image/PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.expensecategory')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalExpense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Motif / Titre')),
                ('amount', models.PositiveIntegerField(verbose_name='Montant (F CFA)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de la dépense')),
                ('notes', models.TextField(blank=True, verbose_name='Notes complémentaires')),
                ('receipt', models.TextField(blank=True, max_length=100, null=True, verbose_name='Justificatif (Image/PDF)')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.expensecategory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Dépense',
                'verbose_name_plural': 'historical Dépenses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
