# Generated by Django 6.0.4 on 2026-04-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expensecategory_alter_audittestmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='backups/', verbose_name='Fichier SQL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backup_type', models.CharField(choices=[('MANUAL', 'Manuelle'), ('AUTO', 'Automatique')], default='AUTO', max_length=10, verbose_name='Type')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
            ],
            options={
                'verbose_name': 'Sauvegarde',
                'verbose_name_plural': 'Sauvegardes',
                'ordering': ['-created_at'],
            },
        ),
    ]
