# Generated by Django 6.0.4 on 2026-04-16 19:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_historicalsale_customer_phone_sale_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='Clé API Wachap')),
                ('api_version', models.CharField(default='v1', max_length=10, verbose_name='Version API')),
                ('manager_phone_1', models.CharField(max_length=20, verbose_name='Numéro Gérant 1')),
                ('manager_phone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro Gérant 2')),
                ('link_validity_hours', models.PositiveIntegerField(default=48, verbose_name='Validité lien (heures)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Communication',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échoué'), ('EXPIRED', 'Expiré')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Message Wachap')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name="Log d'erreur")),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Notification WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
