# Generated by Django 6.0.4 on 2026-04-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_dailyreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationconfig',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='communicationconfig',
            name='api_version',
        ),
        migrations.AddField(
            model_name='communicationconfig',
            name='erp_version',
            field=models.CharField(default='v1.2.0', max_length=20, verbose_name="Version de l'ERP"),
        ),
        migrations.AddField(
            model_name='communicationconfig',
            name='report_time',
            field=models.TimeField(default='20:00', verbose_name='Heure du rapport journalier'),
        ),
        migrations.AddField(
            model_name='communicationconfig',
            name='wachap_instance_id',
            field=models.CharField(default='', max_length=100, verbose_name="ID de l'Instance Wachap"),
        ),
        migrations.AddField(
            model_name='communicationconfig',
            name='wachap_token',
            field=models.CharField(default='', max_length=255, verbose_name='Token / Clé Secrète'),
        ),
        migrations.AlterField(
            model_name='communicationconfig',
            name='manager_phone_1',
            field=models.CharField(default='', max_length=20, verbose_name='Numéro Gérant 1'),
        ),
    ]
