# Generated by Django 6.0.4 on 2026-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_remove_communicationconfig_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationconfig',
            name='developer_test_phone',
            field=models.CharField(blank=True, help_text='Si renseigné, toutes les notifications WhatsApp seront envoyées à ce numéro uniquement (Mode Test).', max_length=20, null=True, verbose_name='Numéro Test Développeur'),
        ),
    ]
