# Generated by Django 6.0.4 on 2026-05-13 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_communicationconfig_developer_test_phone'),
        ('sales', '0007_alter_saleitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappnotification',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sales.sale'),
        ),
    ]
