# Generated by Django 6.0.4 on 2026-05-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_alter_whatsappnotification_sale'),
        ('sales', '0007_alter_saleitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnotification',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sales.payment'),
        ),
    ]
