# Generated by Django 6.0.4 on 2026-04-11 12:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU / Réf interne')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code Barre')),
                ('purchase_price', models.PositiveIntegerField(default=0, verbose_name="Prix d'achat")),
                ('sale_price_piece', models.PositiveIntegerField(default=0, verbose_name='Prix de vente (Pièce)')),
                ('sale_price_carton', models.PositiveIntegerField(default=0, verbose_name='Prix de vente (Carton)')),
                ('conversion_factor', models.PositiveIntegerField(default=1, help_text='Nombre de pièces contenues dans un carton.', verbose_name='Facteur de conversion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Désignation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sku', models.CharField(db_index=True, max_length=50, verbose_name='SKU / Réf interne')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Code Barre')),
                ('purchase_price', models.PositiveIntegerField(default=0, verbose_name="Prix d'achat")),
                ('sale_price_piece', models.PositiveIntegerField(default=0, verbose_name='Prix de vente (Pièce)')),
                ('sale_price_carton', models.PositiveIntegerField(default=0, verbose_name='Prix de vente (Carton)')),
                ('conversion_factor', models.PositiveIntegerField(default=1, help_text='Nombre de pièces contenues dans un carton.', verbose_name='Facteur de conversion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Article',
                'verbose_name_plural': 'historical Articles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
