# Generated by Django 6.0.4 on 2026-04-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouse_alter_historicalproduct_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstocktransaction',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.warehouse', verbose_name='Entrepôt cible (si transfert)'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='inventory.warehouse', verbose_name='Entrepôt cible (si transfert)'),
        ),
        migrations.AlterField(
            model_name='historicalstocktransaction',
            name='quantity',
            field=models.IntegerField(help_text='Quantité en pièces.', verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.IntegerField(help_text='Quantité en pièces.', verbose_name='Quantité'),
        ),
    ]
