# Generated by Django 6.0.4 on 2026-04-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_historicalstocktransaction_to_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alerte quand le stock (en pièces) descend sous ce niveau.', verbose_name="Seuil d'alerte stock"),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alerte quand le stock (en pièces) descend sous ce niveau.', verbose_name="Seuil d'alerte stock"),
        ),
    ]
