# Generated by Django 6.0.4 on 2026-04-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_historicalproduct_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='alert_threshold_cartons',
            field=models.PositiveIntegerField(default=0, help_text="Déclencher une alerte s'il reste moins de X cartons.", verbose_name='Alerte Stock (Cartons)'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='alert_threshold_pieces',
            field=models.PositiveIntegerField(default=5, help_text="Déclencher une alerte s'il reste moins de X pièces.", verbose_name='Alerte Stock (Pièces)'),
        ),
        migrations.AddField(
            model_name='product',
            name='alert_threshold_cartons',
            field=models.PositiveIntegerField(default=0, help_text="Déclencher une alerte s'il reste moins de X cartons.", verbose_name='Alerte Stock (Cartons)'),
        ),
        migrations.AddField(
            model_name='product',
            name='alert_threshold_pieces',
            field=models.PositiveIntegerField(default=5, help_text="Déclencher une alerte s'il reste moins de X pièces.", verbose_name='Alerte Stock (Pièces)'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, verbose_name="Seuil d'alerte global (pièces)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, verbose_name="Seuil d'alerte global (pièces)"),
        ),
    ]
