# Generated by Django 6.0.4 on 2026-04-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_historicalproduct_alert_threshold_cartons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='alert_threshold_cartons',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="Déclencher une alerte s'il reste moins de X cartons.", null=True, verbose_name='Alerte Stock (Cartons)'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='alert_threshold_pieces',
            field=models.PositiveIntegerField(blank=True, default=5, help_text="Déclencher une alerte s'il reste moins de X pièces.", null=True, verbose_name='Alerte Stock (Pièces)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alert_threshold_cartons',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="Déclencher une alerte s'il reste moins de X cartons.", null=True, verbose_name='Alerte Stock (Cartons)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alert_threshold_pieces',
            field=models.PositiveIntegerField(blank=True, default=5, help_text="Déclencher une alerte s'il reste moins de X pièces.", null=True, verbose_name='Alerte Stock (Pièces)'),
        ),
    ]
